module Countries
  protected

  def countries
    @countries = [
     ['Argentina'],
     ['Spain'],
     ['France'],
     ['Germany'],
     ['Italy'],
     ['United Kingdom'],
     ['United States of America'],
     ['--', ' - - - - - - - - - - - - - - -'],
     ['Afghanistan'],
     ['Albania'],
     ['Algeria'],
     ['American Samoa'],
     ['Andorra'],
     ['Angola'],
     ['Anguilla'],
     ['Antarctica'],
     ['Antigua and Barbuda'],
     ['Armenia'],
     ['Aruba'],
     ['Ascension Island'],
     ['Australia'],
     ['Austria'],
     ['Azerbaijan'],
     ['Bahamas'],
     ['Bahrain'],
     ['Bangladesh'],
     ['Barbados'],
     ['Belarus'],
     ['Belgium'],
     ['Belize'],
     ['Benin'],
     ['Bermuda'],
     ['Bhutan'],
     ['Bolivia'],
     ['Bosnia and Herzegovina'],
     ['Botswana'],
     ['Bouvet Island'],
     ['Brazil'],
     ['British Virgin Islands'],
     ['British Indian Ocean Territory'],
     ['Brunei Darussalam'],
     ['Bulgaria'],
     ['Burkina Faso'],
     ['Burundi'],
     ['Cambodia'],
     ['Cameroon'],
     ['Canada'],
     ['Cape Verde'],
     ['ky', 'Cayman Islands'],
     ['Central African Republic'],
     ['Chad'],
     ['Chile'],
     ['China'],
     ['Christmas Island'],
     ['Cocos (Keeling],  Island'],
     ['Colombia'],
     ['Comoros'],
     ['Congo, Republic of'],
     ['Congo, Democratic Republic of'],
     ['Cook Islands'],
     ['Costa Rica'],
     ['Croatia'],
     ['Cuba'],
     ['Cyprus'],
     ['Czech Republic'],
     ['Denmark'],
     ['Djibouti'],
     ['Dominica'],
     ['Dominican Republic'],
     ['Ecuador'],
     ['Egypt'],
     ['El Salvador'],
     ['Equatorial Guinea'],
     ['Eritrea'],
     ['Estonia'],
     ['Ethiopia'],
     ['Falkland Islands (Malvinas], '],
     ['Faroe Islands'],
     ['Fiji'],
     ['Finland'],
     ['French Guiana'],
     ['French Polynesia'],
     ['French Southern Territories'],
     ['Gabon'],
     ['Gambia'],
     ['Georgia'],
     ['Ghana'],
     ['Gibraltar'],
     ['Greece'],
     ['Greenland'],
     ['Grenada'],
     ['Guadeloupe'],
     ['Guam'],
     ['Guatemala'],
     ['Guernsey'],
     ['Guinea'],
     ['Guinea-Bissau'],
     ['Guyana'],
     ['Haiti'],
     ['Heard and McDonald Islands'],
     ['Honduras'],
     ['Hong Kong'],
     ['Hungary'],
     ['Iceland'],
     ['India'],
     ['Indonesia'],
     ['Iran'],
     ['Iraq'],
     ['Ireland'],
     ['Isle of Man'],
     ['Israel'],
     ['Jamaica'],
     ['Japan'],
     ['Jersey'],
     ['Jordan'],
     ['Kazakhstan'],
     ['Kenya'],
     ['Kiribati'],
     ['Korea, North'],
     ['Korea, South'],
     ['Kuwait'],
     ['Kyrgyzstan'],
     ['Laos'],
     ['Latvia'],
     ['Lebanon'],
     ['Lesotho'],
     ['Liberia'],
     ['Libya'],
     ['Liechtenstein'],
     ['Lithuania'],
     ['Luxembourg'],
     ['Macau'],
     ['Macedonia'],
     ['Madagascar'],
     ['Malawi'],
     ['Malaysia'],
     ['Maldives'],
     ['Mali'],
     ['Malta'],
     ['Marshall Islands'],
     ['Martinique'],
     ['Mauritania'],
     ['Mauritius'],
     ['Mayotte'],
     ['Mexico'],
     ['Micronesia'],
     ['Moldova'],
     ['Monaco'],
     ['Mongolia'],
     ['Montserrat'],
     ['Morocco'],
     ['Mozambique'],
     ['Myanmar'],
     ['Namibia'],
     ['Nauru'],
     ['Nepal'],
     ['Netherlands'],
     ['Netherlands Antilles'],
     ['New Caledonia'],
     ['New Zealand'],
     ['Nicaragua'],
     ['Niue'],
     ['Niger'],
     ['Nigeria'],
     ['Norfolk Island'],
     ['Northern Mariana Islands'],
     ['Norway'],
     ['Oman'],
     ['Pakistan'],
     ['Palau'],
     ['Palestinian Territory, Occupied'],
     ['Panama'],
     ['Papua New Guinea'],
     ['Paraguay'],
     ['Peru'],
     ['Philippines'],
     ['Pitcairn Island'],
     ['Poland'],
     ['Portugal'],
     ['Puerto Rico'],
     ['Qatar'],
     ['Reunion'],
     ['Romania'],
     ['Russia'],
     ['Rwanda'],
     ['Saint Helena'],
     ['Saint Kitts and Nevis'],
     ['Saint Lucia'],
     ['Saint Pierre and Miquelon'],
     ['Saint Vincent and the Grenadines'],
     ['Samoa'],
     ['San Marino'],
     ['Sao Tome and Principe'],
     ['Saudia Arabia'],
     ['Senegal'],
     ['Serbia'],
     ['Seychelles'],
     ['Sierra Leone'],
     ['Singapore'],
     ['Slovakia'],
     ['Slovenia'],
     ['Solomon Islands'],
     ['Somalia'],
     ['South Africa'],
     ['Georgia and Sandwich Islands'],
     ['Sri Lanka'],
     ['Sudan'],
     ['Suriname'],
     ['Svalbard and Jan Mayen Islands'],
     ['Swaziland'],
     ['Sweden'],
     ['Switzerland'],
     ['Syria'],
     ['Taiwan'],
     ['Tajikistan'],
     ['Tanzania'],
     ['Thailand'],
     ['Timor-Leste'],
     ['Togo'],
     ['Tokelau'],
     ['Tonga'],
     ['Trinidad and Tobago'],
     ['Tunisia'],
     ['Turkey'],
     ['Turkmenistan'],
     ['Turks and Caicos Islands'],
     ['Tuvalu'],
     ['Uganda'],
     ['Ukraine'],
     ['United Arab Emirates'],
     ['United States Virgin Islands'],
     ['Uruguay'],
     ['US Minor Outlying Islands'],
     ['USSR'],
     ['Uzbekistan'],
     ['Vanuatu'],
     ['Vatican City State'],
     ['Venezuela'],
     ['Vietnam'],
     ['Wallis and Futuna Islands'],
     ['Western Sahara'],
     ['Yemen'],
     ['Yugoslavia'],
     ['Zambia'],
     ['Zimbabwe']]


  end

end


